# .air.toml
# Config file for Air - https://github.com/air-verse/air

# Working directory
root = "."

# Directory to watch for changes
[build]
# We will watch the root directory for changes...
# Files to watch
include_ext = ["go", "html", "txt", "toml", "yml", "yaml", "env"]

# ...and explicitly exclude directories we don't care about.
# This is often more reliable than 'include_dir'.
exclude_dir = ["assets", "tmp", "vendor", "testdata", ".vscode", ".idea", ".git", ".github", "db"]

# We can also exclude specific files in the root.
exclude_file = ["Dockerfile", "Dockerfile.dev", "docker-compose.yml", "docker-compose.dev.yml", "README.md", ".gitignore", ".dockerignore", ".DS_Store", "*.swp", "*.tmp"]

# The build command is correct.
cmd = "go build -buildvcs=false -mod=readonly -o ./tmp/main ./cmd/server"

# Command to run the app
bin = "./tmp/main"
# Add a slight delay to aggregate multiple file save events
delay = 1000 # ms

[log]
# Show log time
time = true

[misc]
# Delete the binary on exit
clean_on_exit = true