version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - govet
    - staticcheck
    - gosec
  disable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0