# Signifies the use of the modern, mandatory configuration schema.
version: "2"

# Controls the runtime behavior of golangci-lint.
run:
  # Set a global timeout for the entire analysis to prevent CI jobs from stalling.
  timeout: 5m

  # Ensure the linter exits with a non-zero code if issues are found.
  issues-exit-code: 1

  # Analyze test files in addition to application code.
  tests: true

  # Use the Go version from the project's go.mod file.
  go: '1.22'

# Configuration for linters (code analysis tools).
linters:
  # Start with all linters disabled and explicitly enable only the desired ones.
  # This "allow-list" approach prevents new, potentially noisy linters from being
  # enabled automatically upon a tool upgrade.
  enable:
    # Core Go tool for finding suspicious constructs.
    - govet
    # Checks for unchecked errors.
    - errcheck
    # A powerful suite of static analysis checks for bugs, performance, and style.
    - staticcheck
    # Reports unused code.
    - unused
    # Checks for misspellings in comments and strings.
    - misspell
    # Enforces a reasonable cyclomatic complexity.
    - gocyclo
    # A highly configurable and performant replacement for golint.
    - revive
    # Security-focused linter.
    - gosec
    # Checks for variables that could be declared as constants.
    - goconst
    # Checks for unhandled errors with database/sql rows.
    - rowserrcheck

# Fine-grained settings for individual linters.

# Configuration for formatters (code styling tools).
formatters:
  enable:
    - gofmt
    - goimports

# Fine-grained settings for individual formatters.

# Configuration for how issues are reported and filtered.
issues:
  # Do not limit the number of reported issues.
  max-issues-per-linter: 0
  max-same-issues: 0

  # Define rules to exclude specific files or directories from certain linters.
