### GET request to check health status
GET http://{{BASE_URL}}}/health

### POST request to register user
POST http://161.118.206.173:8080/api/v1/auth/request-code
Content-Type: application/json

{
  "email": "regysaputra27gmail.com"
}