server {
    listen 80;

    # Your domain (or localhost)
    server_name _;

    resolver 127.0.0.11 valid=10s;
    set $backend "app:8080";

    # Real client IP handling
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Allow WebSockets if needed
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # Pass traffic to Go API
    location / {
        proxy_pass http://$backend;
    }
}